### ISSUE TITLE
Documentation link is invalid and shows on Craft Plugins page

### ISSUE THREAD

**Issue by dougstjohn** [flipboxfactory/craft-link#1]
Steps to Reproduce:
- Go to a Craft CMS install that has the Link plugin installed.
- Go to /admin/settings/plugins
- Find Link plugin and click Documentation.

https://github.com/flipboxfactory/craft-link/blob/c6687b3a523830c05e27ffd0de07d9000ce1b077/composer.json#L48

**Comment by nateiler** [comment]
Fixed via https://github.com/flipboxfactory/craft-link/commit/91f9dd92de693ea42d10afd1a71ded061c6db2c9
