### ISSUE TITLE
Craft 4 support?

### ISSUE THREAD

**Issue by justinholtweb** [flipboxfactory/craft-link#12]
Will this plugin be ported to Craft 4? If so is there an ETA on release for a Craft 4 compatible version?

**Comment by mrwijsman** [comment]
Allmost paid $10 to renew a licence for a dropped plugin.

**Comment by nateiler** [comment]
Sorry for the delay.  We were dragging our feet a bit in hopes that the Craft admin would adopt more Vue components, maybe the next major.

Craft 4 compatibility via: https://github.com/flipboxfactory/craft-link/releases/tag/2.0.0
