### ISSUE TITLE
"Open link in new window" not checked correctly on entries UI

### ISSUE THREAD

**Issue by dougstjohn** [flipboxfactory/craft-link#5]
1. Create a new Link field, add any linktype, and toggle "Show option to open in new window" to ON.
2. Assign the field to an entry.
3. Create a new entry and define a link with "Open link in new window" ON.
4. Save entry and go back in and look at it.
5. "Open link in new window" not checked.

If you have issues reproducing, try creating the link field with the option off, saving, and then going back into the field and turning it on.

**Comment by dougstjohn** [comment]
This causes an entry to lose past settings for this checkbox if ever resaved.

**Comment by nateiler** [comment]
Confirmed and fixed in https://github.com/flipboxfactory/craft-link/releases/tag/1.1.4

The value was getting saved correctly, however the condition to check the box was incorrect.
