### ISSUE TITLE
Target=blank syntax

### ISSUE THREAD

**Issue by dbig** [flipboxfactory/craft-link#7]
Hello,
When the option to open the link in a new window is checked on the entry, the 'target=' parameter is not added to the link in the template code.

Should I be adding code to the template, or is this a bug?  If the former, what is the syntax for the checkbox, as I do not want the target parameter added by default - only when the editor selects a new window.

Thanks very much.

**Comment by nateiler** [comment]
I'll take a look.

In the meantime, are you able to provide an example Twig template code that you're using.  I'll use that to test with.

**Comment by nateiler** [comment]
I performed some tests on Craft v3.5 and Link v1.1.4 and it worked as expected.

In addition to the Twig template code, a snapshot of the field type settings that you've configured and the type of link that you're working with would also be helpful.  

I'll continue troubleshooting once you provide those.

---

**Note**: if you're simply trying to build your own link, here is an example (assuming your field handle is 'hyperlink')
```twig
<a href="{{ entry.hyperlink.url }}" {% if entry.hyperlink.target %} target="{{ entry.hyperlink.target }}"{% endif %}>{{ entry.hyperlink.text }}</a>
```

**Comment by dbig** [comment]
Thanks very much Nate, the {% if entry.hyperlink.target %}{% endif %} is what I was looking for.

Will give that a go.

Are there other elements / arguments when building our own link?  Could you please update the documentation?

Thanks again.

**Comment by nateiler** [comment]
The only attributes that are available across _all_ links would be the public methods found on [Link Type Interface](https://github.com/flipboxfactory/craft-link/blob/master/src/types/TypeInterface.php).

All first party links also have these [public props/methods](https://github.com/flipboxfactory/craft-link/blob/master/src/types/BaseTrait.php).

Some other ways to construct a link can be found here: https://github.com/flipboxfactory/craft-link#templating

We'll work on clarifying the docs a bit.
